#! /bin/sh

NAME={ACCOUNT_NAME}{ACCOUNT_ID}-php-{PHP_NAME}
DESC="{PHP_NAME} PHP Pool"
PIDFILE={PHP_PID}
USER={PHP_USER}
GROUP={PHP_GROUP}
SCRIPTNAME=/etc/init.d/$NAME
 
SPAWN_FCGI={CGI_SPAWN_EXEC}
PHP_INI={PHP_INI}
PHP_FCGI={PHP_EXEC}
PHP_FCGI_CHILDREN={PHP_WORKER_NB_MAX}
PHP_FCGI_MAX_REQUESTS={PHP_WORKER_MAX_REQUESTS}
PHP_FCGI_SOCKET={PHP_SOCK}
PHP_FCGI_SOCKET_USER={WEBSERVER_GROUP}
PHP_FCGI_SOCKET_GROUP={PHP_GROUP}
PHP_FCGI_SOCKET_PERMS=664

. {INIT_SCRIPT_DIR}/php-spawn-fcgi-common.sh
