#!/bin/bash

SITEFOLDER="/home/web/siteadm"
export SITEFOLDER

PHPRC="${SITEFOLDER}/php-config/php.ini"
export PHPRC

PHP_INI_SCAN_DIR="${SITEFOLDER}/php-config/ext"
export PHP_INI_SCAN_DIR

#PHP_FCGI_CHILDREN=8
#export PHP_FCGI_CHILDREN

#PHP_FCGI_MAX_REQUESTS=5000
#export PHP_FCGI_MAX_REQUESTS

exec /usr/bin/php5-cgi
